---
# tasks file for docker-role

 - name: install Docker Engine on Amazon Linux 
   shell: amazon-linux-extras install -y docker
   
 - name: install pip
   yum:
     name: python-pip
   
 - name: install Docker SDK for Python
   pip:
     name: docker

 - name: start Docker
   systemd:
     name: docker
     state: started
     enabled: yes
